import { ReactNode } from 'react';
import type { Metadata } from 'next';

import './globals.css';
import styles from './styles.module.css';

export const metadata: Metadata = {
    title: 'Игрушки ручной работы',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang='ru'>
            <body>
                <main className={styles.page}>{children}</main>
            </body>
        </html>
    );
}
